name: Build u-boots

on:
  workflow_dispatch:
  workflow_call:

jobs:

  Legacy:

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/armbian-framework-uboot-cache.yml@master

    with:

      runner: "ubuntu-latest"
      include: 'grep legacy | '

    secrets:
      token: ${{ secrets.CR_PAT }}
      
  Current:

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/armbian-framework-uboot-cache.yml@master

    with:

      runner: "ubuntu-latest"
      include: 'grep current | '

    secrets:
      token: ${{ secrets.CR_PAT }}

  Edge:

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/armbian-framework-uboot-cache.yml@master

    with:

      runner: "ubuntu-latest"
      include: 'grep edge | '

    secrets:
      token: ${{ secrets.CR_PAT }}
