name: Build u-boots

on:
  workflow_dispatch:
  workflow_call:

env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  Legacy:
    permissions:
      contents: none

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/armbian-framework-uboot-cache.yml@master

    with:

      runner: "ubuntu-latest"
      include: 'grep legacy | '
      
    secrets:     
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  Current:
    permissions:
      contents: none

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/armbian-framework-uboot-cache.yml@master

    with:

      runner: "ubuntu-latest"
      include: 'grep current | '

  Edge:
    permissions:
      contents: none

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/armbian-framework-uboot-cache.yml@master

    with:

      runner: "ubuntu-latest"
      include: 'grep edge | '
