name: Rootfs
on:
  workflow_dispatch:
  workflow_call:

jobs:

  MIN:

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/armbian-framework-rootfs-cache-v2.yml@master

    with:

      minimal: 'yes'
      desktop: 'no'

    secrets:
      token: ${{ secrets.CR_PAT }}
      
  SRV:

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/armbian-framework-rootfs-cache-v2.yml@master

    with:

      minimal: 'no'
      desktop: 'no'

    secrets:
      token: ${{ secrets.CR_PAT }}

  GUI:

    if: ${{ success() && github.repository_owner == 'Armbian' }}
    uses: armbian/scripts/.github/workflows/armbian-framework-rootfs-cache-v2.yml@master

    with:

      minimal: 'no'
      desktop: 'yes'
      
    secrets:
      token: ${{ secrets.CR_PAT }}
